### PR TITLE
Add GPTQModel backend + tokenizer pad fix

### PR DESCRIPTION
**Pull request by CL-ModelCloud**

### CODE REVIEW

**Comment by Qubitium** [comment]
@szq0214 @aidarmyrzakhan PR ready for review:

* Add GPTQModel for optimal gptq quantized model inference. GPTQModel will auto-detect and execute on Nvidia CUDA, Intel XPS, MacOS MPS, Intel/IPEX accelerated CPU (Intel/AMD), and fallback to non-accelerated CPU.
* Fixed tokenizer missing pad_token issue. Some models may not have set the correct pad_token (None) and HF will crash as result. 
* Device arg default "cuda" changed to "auto": GPTQModel has robust auto-mode. For HF,  it will use existing logic of cuda first then cpu.

note: Please squash our PR commits when merging. =)

**Comment by aidarmyrzakhan** [comment]
Thanks very much @CL-ModelCloud @Qubitium!

**Comment by Qubitium** [comment]
> Thanks very much @CL-ModelCloud @Qubitium!

@aidarmyrzakhan You didn't squash merge so all the tiny commits are showing up as individual commits. This puts us as having more commits than original authors. 

Maybe you can squash them on main and do a force push? Just don't want to pollute the commit tree with our `micro` commits. 🤣

**Comment by aidarmyrzakhan** [comment]
@Qubitium Thanks for pointing it out! I've squashed the commits on main.

**Comment by Qubitium** [comment]
@aidarmyrzakhan Sadly your squash action made you the sole author of the commits and we made no contribution in the history. This is strange

**Comment by aidarmyrzakhan** [comment]
@Qubitium Sorry for this one. It is currently fixed.

**Pull request merged**
